### ISSUE TITLE
File reader should check if isis file

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/NeXus-Streamer#76]
In `NexusFileReader.cpp`: 

For ISIS files the name of NXlogs are in the parent classes. We should add a check for ISIS files to set the name of the log to the log object's parent instead of the log itself. ESS files use the name of the log with the log object itself

**Comment by matthew-d-jones** [comment]
Currently the parent group name is used if the `NXlog` group is called `value_log`, a broader check for it being an ISIS file would be more robust.

**Comment by matthew-d-jones** [comment]
Closed by #80
